In [1]:
import cv2

In [2]:
# membaca image
image = cv2.imread("leaf.jpg")

In [3]:
print(image)

[[[249 251 251]
  [251 253 253]
  [251 253 253]
  ...
  [246 246 246]
  [242 242 242]
  [248 248 248]]

 [[245 247 247]
  [247 249 249]
  [249 251 251]
  ...
  [245 245 245]
  [241 241 241]
  [246 246 246]]

 [[248 250 250]
  [250 252 252]
  [251 253 253]
  ...
  [247 247 247]
  [245 245 245]
  [247 247 247]]

 ...

 [[228 235 232]
  [229 236 233]
  [230 237 234]
  ...
  [235 238 236]
  [235 238 236]
  [235 238 236]]

 [[231 238 235]
  [232 239 236]
  [234 241 238]
  ...
  [235 238 236]
  [235 238 236]
  [235 238 236]]

 [[231 238 235]
  [232 239 236]
  [234 241 238]
  ...
  [235 238 236]
  [235 238 236]
  [235 238 236]]]


In [8]:
# menampilkan image
cv2.imshow('leaf', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(image.shape)

(709, 567, 3)


In [6]:
# mengakses nilai di pixel x=100, y=20
(b, g, r) = image[20, 100]
print("blue = ",b)
print("green = ",g)
print("red = ",r)

blue =  249
green =  251
red =  251


In [9]:
# crop image
im_crop = image[100:660, 100:380]

cv2.imshow('crop',im_crop)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(im_crop.shape)

(560, 280, 3)


In [10]:
# mengcopy image
cp_image = image.copy()
print(cp_image.shape)

(709, 567, 3)


In [15]:
# mengubah nilai pixel
cp_image[300:350, 170:300] = (100, 255, 240)

cv2.imshow('cp_image',cp_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# resize image (ignore aspect ratio)
im_resized = cv2.resize(image, (400,400))

cv2.imshow('im_resized',im_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
# resize image (mempertahankan aspect ratio)
r = 400/image.shape[1]
dim = (400,int(image.shape[0]*r))
im_resized = cv2.resize(image, dim)

cv2.imshow('im_resized',im_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# Rotating an image
(h, w) = image.shape[:2]
center = (w/2, h/2)

M = cv2.getRotationMatrix2D(center, 180, 1.0)
rotated = cv2.warpAffine(image, M, (w,h))

cv2.imshow('rotate',rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# menyimpan image
cv2.imwrite("rotate.png", rotated)

True

In [25]:
# adjust image contrast
import numpy as np
im_adjusted = cv2.addWeighted(im_resized, 1.5, np.zeros(im_resized.shape, im_resized.dtype), 0, -100)

cv2.imshow('Original Image',im_resized)
cv2.imshow('Adjusted Image',im_adjusted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
# detect edges
im_edges = cv2.Canny(im_resized, 100, 200)

cv2.imshow('Original Image',im_resized)
cv2.imshow('Detected Edges',im_edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
# convert image to grayscale
im_gray = cv2.cvtColor(im_resized, cv2.COLOR_BGR2GRAY)

cv2.imshow('Original Image',im_resized)
cv2.imshow('Grayscale Image',im_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
# get all files in a folder
import glob

imdir = 'dataset/elephant/'
ext = ['png', 'jpg', 'gif']    # Add image formats here

files = []
[files.extend(glob.glob(imdir + '*.' + e)) for e in ext]

images = [cv2.imread(file) for file in files]

# adjust contrast to all of them nd save to different location
i = 1
for img in images:
    im_adjusted = cv2.addWeighted(img, 1.5, np.zeros(img.shape, img.dtype), 0, -100)
    im_name = "dataset/elephant_contrast/" + str(i) + ".jpg"
    cv2.imwrite(im_name, im_adjusted)
    i+=1